# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2c83cb9e2cb4920720ed3f63924ce702f0ddb5439c7a26fe89216e9c2da0fe747f277dfe98b9cbb8d9bf2e3cb9c222c6ebdd42a8abaac777539f44fc1828ccfb

test:
  secret_key_base: 6a2fad8747fef07a2ac73d56d699a2832362adfb7f6dbc2eb9916d6775799d5e170366a1b4117e9eb72e04c8a2d40af3fe1a7d808de5072528d98e021d3d3230

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
